language: cpp
compiler:
  - gcc
dist: trusty
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y git 
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake
  - sudo apt-get install -y python python-dev
  - sudo apt-get install -y libssl-dev 
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y protobuf-compiler python-protobuf libprotobuf-dev
  - sudo apt-get install -y libcrypto++-dev
  - sudo apt-get install -y liblua5.1-0-dev
  - sudo apt-get install -y libgtest-dev
install:
  - pip install --user jinja2 mkdocs mkdocs-material
script: 
  - mkdir -p tmp
  - pushd tmp 
  - cmake .. 
  - make
after_success:
  - ctest --output-on-failure || exit 1
notifications:
 irc:
  channels:
    - irc.freenode.net#nsclient
  on_success: always
  on_failure: always
  use_notice: true
  skip_join: true
